import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

/**
 * This repository is PUBLIC and is generated by extracting a private
 * application. That extraction is a three-way merge, which means a hunk from
 * the private side lands here verbatim wherever this repo had no conflicting
 * edit of its own.
 *
 * So the failure mode is not "someone types the wrong thing". It is "an
 * upstream comment naming the originating organisation, its database, or a real
 * person arrives silently in a public repo during a routine re-extraction".
 * A sweep run by hand at extraction time does not guard that; it only records
 * that one extraction happened to be clean.
 *
 * That is the same reasoning as logoUsage.test.ts, pointed at identity instead
 * of branding, and it is the cheaper of the two: it needs no database, no
 * network, and no knowledge of what the next leak will look like — only that it
 * will look like one of these.
 */

const ROOT = process.cwd();

/**
 * Tracked files only, from git. Deliberately NOT a filesystem walk: node_modules,
 * .next and a developer's own .env.local are all untracked, and a walk would
 * either scan them (slow, and false positives from third-party licence text) or
 * need an exclusion list that rots.
 */
function trackedFiles(): string[] {
  return execFileSync("git", ["ls-files", "-z"], { cwd: ROOT, encoding: "utf8" })
    .split("\0")
    .filter(Boolean);
}

/** Binary files have no prose to leak, and reading them as UTF-8 invents matches. */
const BINARY = /\.(png|jpe?g|gif|ico|webp|woff2?|ttf|otf|pdf|zip)$/i;

/**
 * Each pattern is a thing that must never appear in a public client template.
 * Keep them specific: a pattern loose enough to match ordinary English (`spine`,
 * `ascend`) produces false positives, and a guard people routinely override is
 * worse than no guard. `ascending` is exactly why these are anchored.
 */
const FORBIDDEN: ReadonlyArray<{ label: string; re: RegExp }> = [
  { label: "originating organisation", re: /\bAscendAI\b|\bAscendlabs\b|ascendlabs\.ai/i },
  { label: "originating org's database", re: /\bAscend Spine\b|\bspine_2026\b|\bleadworks_spine\b/i },
  { label: "originating org's Supabase project ref", re: /fhdhefsvyyokorvuxxyb/i },
  { label: "originating org's other products", re: /\bLeadWorks\b|leadworksai/i },
  { label: "a trust root this schema does not own", re: /public\.user_roles/ },
  { label: "a maintainer's personal address", re: /@kdfaegis\.com|@madbrains\.ai/i },
  // Files the extraction deletes. A surviving reference sends a client to a
  // path that does not exist, which reads as a broken repo.
  { label: "an upstream-only path", re: /\bCLAUDE\.md\b|\bAGENTS\.md\b|\bWBS\.md\b|\bissues\.md\b|supabase\/tests\b|supabase\/template\/|\bDesign\/|\bAscend_MD_files\b/ },
  // Upstream's migrations are timestamped; this template ships 0001/0002 only.
  { label: "an upstream migration filename", re: /\b20\d{12}_[a-z_]+\.sql\b/ },
  // Credential shapes. None of these should ever be committed anywhere.
  { label: "a JWT", re: /eyJhbGciOi/ },
  { label: "a Supabase secret or access token", re: /\bsb_secret_|\bsbp_[a-f0-9]{40}\b/ },
  { label: "a private key block", re: /-----BEGIN [A-Z ]*PRIVATE KEY-----/ },
];

/**
 * Files allowed to contain a pattern, with the reason. Anything not listed here
 * that matches is a failure — an allowlist keyed by file AND pattern, so
 * exempting a file for one reason does not exempt it for every other.
 */
const ALLOWED = new Map<string, ReadonlyArray<string>>([
  // This file names every pattern in order to test for it.
  ["src/lib/templateHygiene.test.ts", FORBIDDEN.map((f) => f.label)],
  // MAINTAINING.md documents the extraction, so it necessarily names the
  // upstream paths it excludes. It names no organisation and no credential.
  ["MAINTAINING.md", ["an upstream-only path", "an upstream migration filename"]],
]);

test("no tracked file leaks the originating organisation, its infrastructure, or a credential", () => {
  const violations: string[] = [];

  for (const file of trackedFiles()) {
    if (BINARY.test(file)) continue;
    const text = readFileSync(path.join(ROOT, file), "utf8");
    const exempt = ALLOWED.get(file) ?? [];

    for (const { label, re } of FORBIDDEN) {
      if (exempt.includes(label)) continue;
      const hit = text.match(re);
      if (hit) {
        const line = text.slice(0, hit.index).split("\n").length;
        violations.push(`${file}:${line} — ${label} (${JSON.stringify(hit[0])})`);
      }
    }
  }

  assert.deepEqual(
    violations,
    [],
    `Identity leak in a PUBLIC template:\n  ${violations.join("\n  ")}\n\n` +
      "This usually means a re-extraction merged an upstream hunk verbatim. Rewrite the\n" +
      "prose — do not add an allowlist entry unless the mention is genuinely necessary.",
  );
});

/**
 * The baseline records which upstream migration it was squashed from. Nothing in
 * this repository can verify that stamp is CURRENT — the guard that does lives
 * in the private upstream. What is verifiable here is that the stamp exists and
 * is well-formed, so a regeneration cannot quietly drop the one piece of
 * provenance a maintainer has to work from.
 */
test("the baseline carries a well-formed provenance stamp", () => {
  const baseline = readFileSync(
    path.join(ROOT, "supabase", "migrations", "0001_baseline.sql"),
    "utf8",
  );
  assert.match(
    baseline,
    /^-- SOURCE-MIGRATION-VERSION: 20\d{12}$/m,
    "0001_baseline.sql must carry a `-- SOURCE-MIGRATION-VERSION: <14-digit>` line",
  );
  assert.match(
    baseline,
    /^-- GENERATED-ON: \d{4}-\d{2}-\d{2}$/m,
    "0001_baseline.sql must carry a `-- GENERATED-ON: <YYYY-MM-DD>` line — a date is the " +
      "one piece of provenance a client can reason about without access to the upstream repo",
  );
});

/**
 * The baseline is applied through the Supabase SQL Editor, which is not psql.
 * pg_dump 17.6+ emits `\restrict`/`\unrestrict`, and any psql meta-command makes
 * the whole file fail on line 1 of the paste. This shipped broken once already.
 */
test("the baseline contains no psql meta-commands", () => {
  const baseline = readFileSync(
    path.join(ROOT, "supabase", "migrations", "0001_baseline.sql"),
    "utf8",
  );
  const offenders = baseline
    .split("\n")
    .map((line, i) => ({ line, n: i + 1 }))
    .filter(({ line }) => /^\\/.test(line));

  assert.deepEqual(
    offenders.map(({ n, line }) => `${n}: ${line}`),
    [],
    "psql meta-commands (lines starting with a backslash) are not SQL. The Supabase SQL " +
      "Editor, the Management API and `supabase db push` all reject them.",
  );
});

/**
 * `SET transaction_timeout` is PostgreSQL 17+. Supabase projects are not all on
 * 17, and an unrecognised SET aborts the entire script before any object is
 * created — the same class of failure as the meta-commands above.
 */
test("the baseline sets no GUC that predates the oldest supported PostgreSQL", () => {
  const baseline = readFileSync(
    path.join(ROOT, "supabase", "migrations", "0001_baseline.sql"),
    "utf8",
  );
  assert.doesNotMatch(
    baseline,
    /^SET transaction_timeout/m,
    "`SET transaction_timeout` is PG17-only and aborts the script on PG15/16. " +
      "pg_dump 17 emits it; strip it after regenerating.",
  );
});
