-- Basecamp template — four starter categories
--
-- WHY THIS IS A SEPARATE FILE. `0001_baseline.sql` is generated by `pg_dump
-- --schema-only --no-owner` and its own header promises schema and no rows. A
-- hand-added INSERT there survives exactly until the next regeneration, then
-- disappears with nothing to say it ever existed. Rows belong in a file no
-- generator writes.
--
-- APPLY IT AFTER `0002_security_boundary.sql`, not before. `0002` is the gate
-- that says the schema is sound — it pins ownership, hardens the definer
-- functions and asserts the boundary — and seeding a schema that failed that
-- check puts data into something you already know is wrong. Nothing here
-- touches the boundary: no table, no policy, no function, no grant. `0002`
-- counts objects, never rows, so the order between them is a matter of sense
-- rather than of correctness.
--
-- OPTIONAL. The app works with an empty `basecamp.categories`; the Catalog
-- admin screen can create categories from nothing. This file exists so a client
-- reaching their new app for the first time finds somewhere to put their first
-- entry instead of an empty page and a blank form.
--
-- IDEMPOTENT, AND SPECIFICALLY `do nothing` RATHER THAN `do update`. Run it as
-- many times as you like. What that choice buys, and what it costs, both matter
-- enough to state:
--
--   * A RENAME SURVIVES. The conflict target is `slug`, and a re-run leaves the
--     existing row entirely alone — so a client who renames "Sales" to "New
--     business" keeps that name through any number of re-applies. `do update`
--     would silently undo their first customisation of the app, which is the
--     one the guided walkthrough asks them to make.
--   * A DELETE DOES NOT. Re-running recreates a category the client deliberately
--     removed, because an absent slug is indistinguishable from a never-seeded
--     one. This file cannot tell those apart and does not try. Provisioning runs
--     once, so the cost is bounded; if you re-run it later and a deleted
--     category returns, that is this line and not a bug.
--
-- The four names are a starting point, not a taxonomy. Rename them, reorder
-- them, delete the ones that do not fit — that is what Admin → Catalog is for.

begin;

-- `description` is NOT NULL with a `length(btrim(...)) > 0` CHECK, so every row
-- has to carry a real sentence. These are written for the person who lands on
-- the catalog with nothing in it yet: each one says what belongs here, because
-- an empty category whose name is a single word gives no hint about what to put
-- in it.
--
-- `sort_order` is spaced by 10. It is NOT unique and it defaults to 0, and the
-- app always orders by `(sort_order, slug)` — the gaps are what let a category
-- be dropped between two others later without renumbering the rest. The same
-- convention the app uses when it creates a category of its own.
--
-- Slugs are the conflict target and are therefore the stable identity here: they
-- must satisfy `^[a-z0-9]+(-[a-z0-9]+)*$`, and `useful-tools` is the only one of
-- the four that needs the hyphen.
insert into basecamp.categories (slug, name, description, sort_order)
values
  ('sales',        'Sales',
   'Anything used to find, track or close business — pipelines, proposals, quotes and the tools around them.',
   10),
  ('marketing',    'Marketing',
   'How the organisation is seen and heard: the website, campaigns, content, and the analytics behind them.',
   20),
  ('operations',   'Operations',
   'The machinery that keeps the organisation running day to day — scheduling, invoicing, reporting and internal process.',
   30),
  ('useful-tools', 'Useful Tools',
   'Everything that does not belong to one team: shared utilities, references and the small things everyone reaches for.',
   40)
on conflict (slug) do nothing;

-- A seeded category starts with NO ENTRIES, and that has one visible
-- consequence worth knowing before you go looking for a bug:
--
--   `basecamp.category_has_grant()` requires a category to contain at least one
--   entry the caller may read. That entry-existence test is deliberate — a grant
--   on an empty category must disclose nothing, not even the category's name —
--   so an ordinary team member sees NONE of these four until entries exist and
--   they have been granted something inside one.
--
-- A super_admin READS all four immediately, because the SELECT policy on
-- `categories` short-circuits on `is_super_admin()` before it ever consults
-- `category_has_grant`. That is what makes **Admin → Catalog** usable on a
-- brand-new install: it queries `categories` directly and lists all four with
-- their entry counts, which is where the guided walkthrough's "rename a
-- category" step happens.
--
-- READ IS NOT SHOWN, and an earlier version of this comment stopped one step
-- short. The HOME screen renders none of them, for a super_admin as much as for
-- anyone: `src/lib/catalog.ts` drops every category with no entries —
-- `filter((c) => (c.entries?.length ?? 0) > 0)` — and that function receives
-- rows and nothing else, so it has no viewer to make an exception for. A fresh
-- administrator's first home screen is the "Your catalog is empty" panel
-- whether or not this file ran. Put an entry in a category and it appears.

commit;
